name: Node.js CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
